# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Todo Pasa
email: todopasa@oceano.uy
author: Danilo Espino
whatsapp: 59893600051
description: >- # this means to ignore newlines until "baseurl:"
  Los podcasts de Todo Pasa.
description-coqueto: >- # this means to ignore newlines until "baseurl:"
  Todas las columnas de Lubo Adusto Freire.
description-musica: # this means to ignore newlines until "baseurl:"
  Todas las columnas de música de César Ernesto Sanguinetti.
baseurl: "/todopasa" # the subpath of your site, e.g. /blog
url: "https://despinouy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
showsite: "https://oceano.uy/todopasa"
twitter_username: todopasaoceano
facebook_username: todopasaoceano
lang: es

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 3
paginate_path: "/blog/:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
